CREATE TABLE SYS_PESQUISADOR (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USUARIO_ID BIGINT NOT NULL,
	METODOAGRUPAMENTO VARCHAR(50) NOT NULL,
	INTERVALOCONFIANCA INT NOT NULL,
	PREENCHERCELULASVAZIAS BIT DEFAULT 1
);

ALTER TABLE SYS_PESQUISADOR 
ADD CONSTRAINT SYS_PESQUISADOR_REFERENCES_SYS_USUARIO_0001
FOREIGN KEY (USUARIO_ID) REFERENCES SYS_USUARIO (ID);

INSERT INTO SYS_PESQUISADOR (ID, USUARIO_ID, METODOAGRUPAMENTO, INTERVALOCONFIANCA)
	VALUES (1, 1, 'MANTEL_HAENSZEL', 95);